# Generated by Django 4.2.16 on 2024-12-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='download_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
